spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uni
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

univCert:
  key: 0a44d2bc-1cae-4991-a5e1-41884894b333
