name: Java CI with Gradle

on:
  push:
    branches: [ "main", "dev" ]  # 테스트를 위해 dev 브랜치에서만 작동 
  pull_request:
    branches: [ "main", "dev" ]  # 테스트를 위해 dev 브랜치에서만 작동
    types: [closed]
#on:
  #push:
    #branches: 
      #- "2-도커-및-devops"  # 테스트를 위해 이 브랜치에서 푸시될 때 작동
      #- "5-깃허브-액션"      # 테스트를 위해 이 브랜치에서도 푸시될 때 작동
  #pull_request:
    #branches: 
      #- "2-도커-및-devops"  # 테스트를 위해 이 브랜치에서 PR이 열릴 때 작동
      #- "5-깃허브-액션"      # 테스트를 위해 이 브랜치에서도 PR이 열릴 때 작동

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: uni
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set execute permission on gradlew
      run:  chmod +x ./gradlew

    # Gradle 빌드
    - name: Build with Gradle
      run: ./gradlew clean build 

    # Docker 이미지 빌드
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/uni:latest .

    # Docker 로그인
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Docker 이미지 푸시
    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/uni:latest
